//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zorgcirckel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class antwoord
    {
        public int AntwoordID { get; set; }
        public int VraagID { get; set; }
        public string Antwoord1 { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public string AspNetUsersID { get; set; }
        public Nullable<int> LijstID { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Vragen Vragen { get; set; }
    }
}
