//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zorgcirckel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetUsers()
        {
            this.antwoord = new HashSet<antwoord>();
            this.Contacten = new HashSet<Contacten>();
            this.Contacten1 = new HashSet<Contacten>();
            this.Incidenten = new HashSet<Incidenten>();
            this.Rapportages = new HashSet<Rapportages>();
            this.Incidenten1 = new HashSet<Incidenten>();
            this.Rapportages1 = new HashSet<Rapportages>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public string Voornaam { get; set; }
        public string Achternaam { get; set; }
        public string Geslacht { get; set; }
        public Nullable<System.DateTime> Geboortdatum { get; set; }
        public string Adres { get; set; }
        public string Woonplaats { get; set; }
        public string Postcode { get; set; }
        public string Gemeente { get; set; }
        public string Geboorteplaats { get; set; }
        public string Nationaliteit { get; set; }
        public string BSNNummer { get; set; }
        public string Verzekering { get; set; }
        public string Huisarts { get; set; }
        public Nullable<bool> Reanimatiebeleid { get; set; }
        public string ReanimatieOpmerking { get; set; }
        public Nullable<bool> JuridischeStatus { get; set; }
        public string BurgelijkeStatus { get; set; }
        public Nullable<bool> Gezin { get; set; }
        public string Scholing { get; set; }
        public string Werk { get; set; }
        public Nullable<bool> Religie { get; set; }
        public string ReligieOpmerking { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public string Straatnaam { get; set; }
        public Nullable<int> Huisnunmmer { get; set; }
        public Nullable<bool> Financien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<antwoord> antwoord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contacten> Contacten { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contacten> Contacten1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incidenten> Incidenten { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rapportages> Rapportages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incidenten> Incidenten1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rapportages> Rapportages1 { get; set; }
    }
}
